# Generated by Django 3.2 on 2021-05-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectTask', '0003_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photoFileName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
