# Generated by Django 3.2 on 2021-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectTask', '0005_alter_project_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photoFileName',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
